# Generated by Django 4.0.5 on 2022-07-23 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_dios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dios',
        ),
    ]
