# Generated by Django 4.0.5 on 2022-07-30 21:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_publicaciones_imagenes_delete_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='contenido',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
