# Generated by Django 4.0.5 on 2022-07-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_delete_dios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('sub_titulo', models.CharField(max_length=250)),
                ('contenido', models.CharField(max_length=500)),
                ('autor', models.CharField(max_length=500)),
                ('fecha_creacion', models.DateField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
